# CI runs: golangci-lint. Branch protection requires "Lint" to pass before merge.
version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
