# Run locally: make lint. Not run in CI (golangci-lint-action binary targets Go 1.24; this repo uses Go 1.26).
version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
